accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"forget/$", views.Forget.as_view(), name="forget"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    url(r"list/$",views.TestViewGeneric.as_view(), name="list"),
]

simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <style type="text/css">
      .scrollable {
        height: 770px;
        overflow-y: scroll;

      }

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>College Based Social Network</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'simplesocial/css/masters.css'%}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

</head>

  <body>
    <div class="scrollable">
    <nav class="navbar  navbar-inverse" role="navigation" id="navbar">

    			<div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'images/classmatess.jpg'%}" alt="logo" width="65px">
               </a>
           <a class="navbar-brand mynav"a href="{% url 'home' %}"> College Based Social Network</a>
            </div>
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>

    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <!-- <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                      <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %} {% endblock %}
        </div>
<canvas id="canvas"></canvas>
  </body>
<script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  
</div>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{%load staticfiles%}

<div class="jumbotron">
<div class="row">
  <div class="col-sm-6">
    <img src="{% static 'images/connecting.jpg'%}" alt="logo" align="left" width="450px"><br>
    </div>
   <div class="col-sm-6">
     <font size="3" color="black"><h2><b>Welcome to College Based Social Network!</b></h2><br>College Based Social Network provides the students of college to form a social networking platform among themselves, enabling them to connect with their seniors and juniors for sharing of information and resources. College Based Social Network is helpful to remove communication gap between seniors and juniors
     Its goal is to make a communication bridge between seniors and juniors .It provides user features to follow the students, send message to others.
     </font>
   </div>
</div>
</div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <font size="0" color="black">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>
   </font>

</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<font size="0" color="black"><h1>Thanks for visiting! Come back soon!</h1></font>
{% endblock %}